Repository tum-ai/website, pull requests merged in 2024-08, with the labels that each got.

#122 feat: structured data added
  app/e-lab/[id]/page.tsx
  app/e-lab/page.tsx
  app/page.tsx
  data/e-lab.tsx
  package.json
Labels: feature, Ready for merge

#119 feat: add google analytics banner without measurement ID
  app/layout.tsx
  components/CookieBanner.tsx
  components/GoogleAnalytics.tsx
  components/lib/cookieStorage.ts
  components/lib/gtagHelper.ts
  package.json
Labels: feature

#123 feat: e-lab application phase 3.0 form added
  app/e-lab/hero.tsx
  app/page.tsx
Labels: Ready for merge
